name: shopify_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.10+1
  graphql_flutter: ^5.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0
  flutter_launcher_icons: ^0.14.2
  connectivity_plus:
  intl_phone_number_input:
  sqflite: ^2.2.1
  path: ^1.8.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.3


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/mnb_icon.png"


flutter: 
  uses-material-design: true

  assets:
    - .env
    - assets/social-icons/facebook.svg
    - assets/social-icons/instagram.svg
    - assets/social-icons/tiktok.svg
    - assets/social-icons/x.svg
    - assets/social-icons/youtube.svg
